# mybatis-plus相关配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*.xml
  # 如果是放在resource目录 classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mobinming.springvoot.entity
  global-config:
    db-config:
      # AUTO(0)数据库ID自增  NONE(1)该类型为未设置主键类型(将跟随全局)  INPUT(2)用户输入ID
      id-type: INPUT
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-demo-db?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver #直接打mysql会有提示