spring:
  #jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-demo-db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#mybatis配置
mybatis:
  #映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #模型所在的保命
  type-aliases-package: com.mobinming.springboot.entity
